### ISSUE TITLE
Add linter configuration file

### ISSUE THREAD

**Issue by rchl** [daveleroy/sublime_db#12]
When I open source code in my editor, which has pycodestyle running by default, almost whole code shows issues due to using tab for indentation.

<img width="471" alt="pylint" src="https://user-images.githubusercontent.com/153197/47861378-f9593f80-ddf2-11e8-8cb8-24f6b4b5f33d.png">

Can we add a configuration for pycodestyle that matches expected code style? Would help contributors too.

**Comment by daveleroy** [comment]
Done. setup.cfg now has a pycodestyle section and the whole project has been formatted
