### ISSUE TITLE
configurations in user's settings are ignored

### ISSUE THREAD

**Issue by AmjadHD** [daveleroy/sublime_db#15]
I have a folder named "Test Debugger" that contains a single file named "test_python_debugger.py"
and I have this in my User/debug.sublime-settings :
```json
{
    "configurations":
[
    {
        "name": "Python Debug",
        "type": "python",
        "request": "launch",
        "program": "${file}",
        "debugOptions" : {
            "RedirectOutput": true,
        }
    },
]
}
```
running `Debugger: Open` in the command palette then start debugging (play icon in the panel)
the configuration does not appear (only `--Add Configurations--`), but when putting the configurations in the project file it is accepted (`Python Debug` entry appears).

OS: Windows 7
sublime_db: latest master.

**Comment by daveleroy** [comment]
Closing for now. I have disabled the ability to open a debugger outside of a project. It will probably be added back in later but it requires a decent bit of work to make work nicely.

**Comment by daveleroy** [comment]
If you want this feature you can open an issue to track its progress
