### ISSUE TITLE
Normal views instead of phantoms ?!

### ISSUE THREAD

**Issue by predragnikolic** [daveleroy/sublime_db#9]
Hello Leroy, 
Nice to see that you open-sourced it :)

Even through I think the phantom panel looks awesome and unique. 
I think that it would be more useful and more easier to maintain that you used a normal view grid layout like for example xdebug for sublime.

![](http://www.vaerenbergh.com/sites/default/files/Screenshot-xdebug-2.png)

You could use the layout just to make the columns for the `Call Stack`, `Variables`, `Event Log` and the first panel (witch I don't know how it is called). And for the rest of the stuff you could populate each view with a phantom?

You could use fold regions for traversing tree like objects, and each view is independently scrollable. which is not the case with the current implementation. (sometimes I can't even scroll beyond a certain point, see image bellow)
![2018-10-31-134556_1366x768_scrot](https://user-images.githubusercontent.com/22029477/47789285-73ff5d80-dd14-11e8-9288-62b63ddeb46f.png)

So the question is what do you think about a grid view layout?
I think it is better to ask you that now, than later.

**Comment by predragnikolic** [comment]
Thank you for the answer. :)

There is no need for a change now.

**Comment by predragnikolic** [comment]
I know I closed this.
But I would like to know if you would find something like this usefull https://github.com/SublimeTextIssues/Core/issues/2479 ?

**Comment by daveleroy** [comment]
Yeah that would be really useful since the tabs take up a ton of space. I think the minimap also can't be disabled per view which seems wrong to me.

**Comment by predragnikolic** [comment]
Thanks for your response :-)
